postgresinit:
	docker run --name postgres15 -p 5433:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=password -d postgres:15.6-alpine3.18
.PHONY: postgresinit

postgresstop:
	docker stop postgres15
.PHONY: postgresstop

postgres:
	docker exec -it postgres15 psql --username=root --dbname=musicdb
.PHONY: postgres 

createdb:
	docker exec -it postgres15 createdb --username=root --owner=root musicdb
.PHONY: createdb